#Broadcast插件配置文件
#作者QQ 583308121

#公告的前缀,显示在公告具体内容之前,如果要使用彩色代码,应当用§
Prefix: '§3[公告]'
#公告内容
BroadcastContent:
  - '这是一条默认语句'
  - '这是第二条默认语句'
#是否启用自动公告功能
enable_Timer: False
#每隔多少秒自动公告一次(前提是enable_timer打开)
Timer: 5