name: Broadcast
version: '${project.version}'
main: com.xiaye.broadcast.Broadcast
api-version: 1.18
authors: [ Xiaye ]
description: A simple way to broadcast
commands:
  xbc:
    description: 发送WorldCraft命令
    permission: broadcast.xbc
  bcreload:
    description: 重载配置文件
    permission: broadcast.bcreload
  rbc:
    description: 随机发送公告
    permission: broadcast.rbc
permissions:
  broadcast.*:
    description: Broadcast的所有权限
    children:
      broadcast.xbc: true
  broadcast.xbc:
    description: 允许使用/xbc命令
    default: op
  broadcast.bcreload:
    description: 允许使用/bcreload命令
    default: op
  broadcast.rbc:
    description: 允许使用/rbc命令
    default: op
